spring.application.name=inventory
server.port=9001

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=sa
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Console http://localhost:9001/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
